# Generated by Django 5.1.5 on 2025-02-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsubtopmenu',
            name='subTopMenuImage',
        ),
        migrations.RemoveField(
            model_name='tbltopmenu',
            name='topMenuImage',
        ),
    ]
