# Generated by Django 5.1.5 on 2025-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_tblsubtopmenu_subtopmenuimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblproducts',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
